version: '3.9'
services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: app_development

  web:
    build: .
    command: bash -c "./entrypoint.sh"
    environment:
      RAILS_ENV: development
    volumes:
      - .:/rails
    ports:
      - "3001:3000"
    depends_on:
      - db

volumes:
  db_data:
