default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_development
  username: postgres
  password: password
  host: db
  port: 5432

test:
  <<: *default
  database: myapp_test
  username: postgres
  password: password
  host: db
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>